#!/bin/sh

# Way to kill process in the current display
# Based on https://unix.stackexchange.com/a/181371
ActiveProcessPID()
{
        local process="$1"

        local processPIDs="$(pidof -s "$process")"

        local displayNumber="$(echo $DISPLAY \
                | awk 'BEGIN { FS = "[:.]" } { print $2 }')"

        ps e -p "$processPIDs" \
                | awk -v n="$displayNumber" \
                        '$0 ~ " DISPLAY=:" n "[\n .]" { print $1 }'
}

# Spams kill till the process doesn't exist
KillPID()
{
	while true; do
		kill "$(ActiveProcessPID "$1" 2>/dev/null)" 2>/dev/null || break
	done
}

# Kill the clock
KillPID xclock

# Kill the welcome text and power buttons
KillPID xmessage

# Set background to black
xsetroot -solid black

# Execute normal Xstartup
exec /etc/X11/xdm/Xstartup
